import express from 'express';
import dotenv from 'dotenv';
import Razorpay from 'razorpay';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import nodemailer from 'nodemailer';

dotenv.config();
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const ROOT=path.join(__dirname,'..');
const DATA=path.join(__dirname,'data');
const LICENSE_FILE=path.join(DATA,'licenses.json');
const PAYMENT_FILE=path.join(DATA,'payments.json');
const REQUEST_FILE=path.join(DATA,'renewal-requests.json');
fs.mkdirSync(DATA,{recursive:true});
for(const f of [LICENSE_FILE,PAYMENT_FILE,REQUEST_FILE])if(!fs.existsSync(f))fs.writeFileSync(f,'[]');
const readJson=f=>JSON.parse(fs.readFileSync(f,'utf8'));
const writeJson=(f,x)=>fs.writeFileSync(f,JSON.stringify(x,null,2));
const licenses=()=>readJson(LICENSE_FILE), payments=()=>readJson(PAYMENT_FILE), requests=()=>readJson(REQUEST_FILE);
const saveLicenses=x=>writeJson(LICENSE_FILE,x), savePayments=x=>writeJson(PAYMENT_FILE,x), saveRequests=x=>writeJson(REQUEST_FILE,x);
const app=express();
app.use((req,res,next)=>{res.header('Access-Control-Allow-Origin',process.env.FRONTEND_ORIGIN||'*');res.header('Access-Control-Allow-Headers','Content-Type,Authorization,X-Admin-Token');res.header('Access-Control-Allow-Methods','GET,POST,OPTIONS');if(req.method==='OPTIONS')return res.sendStatus(204);next()});
app.use('/webhooks/razorpay',express.raw({type:'application/json'}));
app.use(express.json({limit:'1mb'}));
app.use(express.static(ROOT));
const keyId=process.env.RAZORPAY_KEY_ID||'';
const keySecret=process.env.RAZORPAY_KEY_SECRET||'';
const webhookSecret=process.env.RAZORPAY_WEBHOOK_SECRET||'';
const adminToken=process.env.ADMIN_ACTIVATION_TOKEN||'';
const razorpay=(keyId&&keySecret)?new Razorpay({key_id:keyId,key_secret:keySecret}):null;
const renewalAmount=days=>days>100?Number(process.env.YEARLY_RENEWAL||1999):Number(process.env.MONTHLY_RENEWAL||299);
function sign(orderId,paymentId){return crypto.createHmac('sha256',keySecret).update(orderId+'|'+paymentId).digest('hex')}
function upsertLicense(customerId,days,orderId='',paymentId=''){const list=licenses();let l=list.find(x=>x.customerId===customerId);const base=l&&l.expiry&&new Date(l.expiry)>new Date()?new Date(l.expiry):new Date();base.setDate(base.getDate()+days);const out={customerId,plan:days>100?'Yearly':'Monthly',status:'ACTIVE',expiry:base.toISOString(),orderId,paymentId,updatedAt:new Date().toISOString()};if(l)Object.assign(l,out);else list.push(out);saveLicenses(list);return out}
function recordPayment(p){const list=payments();if(!list.some(x=>x.paymentId===p.paymentId)){list.push(p);savePayments(list)}}
function requireAdmin(req,res,next){if(!adminToken)return res.status(503).json({error:'ADMIN_ACTIVATION_TOKEN is not configured on server.'});if(req.headers['x-admin-token']!==adminToken)return res.status(401).json({error:'Invalid admin activation token.'});next()}
async function sendRenewalEmail(request){const host=process.env.SMTP_HOST,user=process.env.SMTP_USER,pass=process.env.SMTP_PASS,to=process.env.NOTIFY_EMAIL||user;if(!host||!user||!pass||!to)return {sent:false,reason:'SMTP not configured'};try{const transporter=nodemailer.createTransport({host,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE||'false')==='true',auth:{user,pass}});await transporter.sendMail({from:process.env.SMTP_FROM||user,to,subject:'Hotel renewal payment request - '+request.customerId,text:'Renewal request received. Customer: '+request.customerName+' | License: '+request.customerId+' | Plan: '+request.plan+' | Amount: ₹'+request.amount+' | UTR: '+request.utr+' | Mobile: '+request.mobile+' | Paid at: '+request.paidAt});return {sent:true}}catch(e){return {sent:false,reason:e.message}}}
app.get('/api/health',(req,res)=>res.json({ok:true,paymentConfigured:!!razorpay,manualRenewalConfigured:!!adminToken}));
app.get('/api/subscription/status/:customerId',(req,res)=>{const l=licenses().find(x=>x.customerId===req.params.customerId);res.json({active:!!l&&l.status==='ACTIVE'&&new Date(l.expiry)>new Date(),subscription:l||null})});
app.post('/api/subscription/create-order',async(req,res)=>{try{if(!razorpay)return res.status(503).json({error:'Payment gateway is not configured on the server.'});const customerId=String(req.body.customerId||'').trim();const days=Number(req.body.days);if(!customerId||![30,365].includes(days))return res.status(400).json({error:'Invalid renewal data.'});const amount=renewalAmount(days);const order=await razorpay.orders.create({amount:Math.round(amount*100),currency:'INR',receipt:'renew_'+customerId.slice(0,20)+'_'+Date.now(),notes:{customerId,days:String(days),type:'hotel_license_renewal'}});res.json({key:keyId,order});}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/subscription/verify',async(req,res)=>{try{if(!razorpay)return res.status(503).json({error:'Gateway not configured.'});const {razorpay_order_id,razorpay_payment_id,razorpay_signature}=req.body||{};if(!razorpay_order_id||!razorpay_payment_id||!razorpay_signature)return res.status(400).json({error:'Missing payment verification fields.'});if(sign(razorpay_order_id,razorpay_payment_id)!==razorpay_signature)return res.status(400).json({error:'Invalid payment signature.'});const order=await razorpay.orders.fetch(razorpay_order_id);const notes=order.notes||{};const customerId=String(notes.customerId||'').trim();const days=Number(notes.days);if(!customerId||![30,365].includes(days))return res.status(400).json({error:'Trusted renewal order details not found.'});const sub=upsertLicense(customerId,days,razorpay_order_id,razorpay_payment_id);recordPayment({type:'subscription',customerId,orderId:razorpay_order_id,paymentId:razorpay_payment_id,amount:Number(order.amount)/100,createdAt:new Date().toISOString()});res.json({ok:true,active:true,subscription:sub});}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/payments/create-order',async(req,res)=>{try{if(!razorpay)return res.status(503).json({error:'Payment gateway is not configured.'});const customerId=String(req.body.customerId||'').trim()||'HOTEL-GUEST';const amount=Number(req.body.amount);if(!Number.isFinite(amount)||amount<=0)return res.status(400).json({error:'Invalid amount.'});const order=await razorpay.orders.create({amount:Math.round(amount*100),currency:'INR',receipt:'inv_'+Date.now(),notes:{type:'hotel_invoice_payment',customerId,bookingNo:String(req.body.bookingNo||''),invoiceNo:String(req.body.invoiceNo||'')}});res.json({key:keyId,order});}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/payments/verify',(req,res)=>{try{if(!razorpay)return res.status(503).json({error:'Gateway not configured.'});const {razorpay_order_id,razorpay_payment_id,razorpay_signature,bookingNo,invoiceNo,amount}=req.body||{};if(sign(razorpay_order_id,razorpay_payment_id)!==razorpay_signature)return res.status(400).json({error:'Invalid payment signature.'});recordPayment({type:'invoice',bookingNo,invoiceNo,paymentId:razorpay_payment_id,orderId:razorpay_order_id,amount:Number(amount),createdAt:new Date().toISOString()});res.json({ok:true,paid:true,reference:razorpay_payment_id});}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/renewal-requests',async(req,res)=>{try{const customerId=String(req.body.customerId||'').trim(),customerName=String(req.body.customerName||'').trim(),mobile=String(req.body.mobile||'').trim(),plan=String(req.body.plan||'').trim(),utr=String(req.body.utr||'').trim(),paidAt=String(req.body.paidAt||'').trim();const days=Number(req.body.days),amount=Number(req.body.amount);if(!customerId||!customerName||!mobile||!utr||![30,365].includes(days)||!Number.isFinite(amount)||amount<=0)return res.status(400).json({error:'Customer, mobile, plan, amount and UTR are required.'});const expected=renewalAmount(days);if(Math.abs(amount-expected)>0.01)return res.status(400).json({error:'Renewal amount does not match server price.'});const list=requests();if(list.some(x=>x.status==='PENDING'&&x.utr===utr))return res.status(409).json({error:'This UTR is already submitted.'});const r={id:crypto.randomUUID(),customerId,customerName,mobile,plan:days>100?'Yearly':'Monthly',days,amount,utr,paidAt:paidAt||new Date().toISOString(),status:'PENDING',createdAt:new Date().toISOString()};list.unshift(r);saveRequests(list);const email=await sendRenewalEmail(r);res.json({ok:true,request:r,notification:email});}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/renewal-requests',requireAdmin,(req,res)=>res.json({requests:requests()}));
app.post('/api/renewal-requests/:id/verify',requireAdmin,(req,res)=>{try{const list=requests(),r=list.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({error:'Renewal request not found.'});if(r.status==='VERIFIED'){const l=licenses().find(x=>x.customerId===r.customerId);return res.json({ok:true,active:true,subscription:l})}const sub=upsertLicense(r.customerId,r.days,'MANUAL-'+r.id,r.utr);r.status='VERIFIED';r.verifiedAt=new Date().toISOString();saveRequests(list);recordPayment({type:'manual_subscription',customerId:r.customerId,orderId:'MANUAL-'+r.id,paymentId:r.utr,amount:r.amount,createdAt:new Date().toISOString(),source:'manual_utr_verified'});res.json({ok:true,active:true,subscription:sub});}catch(e){res.status(500).json({error:e.message})}});
app.post('/webhooks/razorpay',(req,res)=>{try{if(!webhookSecret)return res.status(503).send('Webhook secret not configured');const raw=req.body;const sig=req.headers['x-razorpay-signature'];const expected=crypto.createHmac('sha256',webhookSecret).update(raw).digest('hex');if(sig!==expected)return res.status(400).send('Invalid webhook signature');const event=JSON.parse(raw.toString('utf8'));const p=event.payload?.payment?.entity;if(event.event==='payment.captured'&&p){const notes=p.notes||{};if(notes.type==='hotel_license_renewal'){const customerId=notes.customerId||'HOTEL-DEMO';const days=Number(notes.days||renewalDays(Number(p.amount)/100));const already=payments().some(x=>x.paymentId===p.id);if(!already){upsertLicense(customerId,days,p.order_id,p.id);recordPayment({type:'subscription',customerId,orderId:p.order_id,paymentId:p.id,amount:Number(p.amount)/100,createdAt:new Date().toISOString(),source:'webhook'});}}}res.json({ok:true});}catch(e){res.status(500).send('Webhook error')}});
app.get('/{*splat}',(req,res)=>res.sendFile(path.join(ROOT,'index.html')));
const port=Number(process.env.PORT||8080);app.listen(port,()=>console.log('Hotel Management server running on http://localhost:'+port));
